9lev:
  colours:  
    common: ["#C7EAF4", "#9DD4E2", "#FEF5AA", "#F3C848", "#D8620B", "#862716"]
  contour_levels:
    ozone: [0, 50, 100, 130, 240, 380, 1000]
    particulate_matter_2.5um: [0, 10, 20, 25, 50, 75, 1000]
    particulate_matter_10um: [0, 20, 40, 50, 100, 150, 1200]
    nitrogen_dioxide: [0, 40, 90, 120, 230, 340, 1000]
    sulphur_dioxide: [0, 100, 200, 350, 500, 750, 1250]
eea:
  colours:  
    ozone: ["#C7EAF4", "#9DD4E2", "#F3C848", "#D8620B", "#862716"]
    particulate_matter_2.5um: ["#C7EAF4", "#9DD4E2", "#F3C848", "#D8620B", "#862716"]
    particulate_matter_10um: ["#C7EAF4", "#9DD4E2", "#F3C848", "#D8620B", "#862716"]
    nitrogen_dioxide: ["#C7EAF4", "#9DD4E2", "#F3C848", "#D8620B", "#862716"]
    alder_pollen: ["#EFEEEC", "#A0D7FF", "#47B3FF", "#FEF6CD", "#FBEC9B", "#FAC50D", "#FF9933", "#E56B38", "#B83230", "#5C1918"]
    birch_pollen: ["#EFEEEC", "#A0D7FF", "#47B3FF", "#FEF6CD", "#FBEC9B", "#FAC50D", "#FF9933", "#E56B38", "#B83230", "#5C1918"]
    grass_pollen: ["#EFEEEC", "#A0D7FF", "#FEF6CD", "#FBEC9B", "#FAC50D", "#FF9933", "#E56B38", "#B83230", "#5C1918"]
    mugwort_pollen: ["#EFEEEC", "#A0D7FF", "#47B3FF", "#FEF6CD", "#FBEC9B", "#FAC50D", "#FF9933", "#E56B38", "#B83230", "#5C1918"]
    olive_pollen: ["#EFEEEC", "#A0D7FF", "#47B3FF", "#FEF6CD", "#FBEC9B", "#FAC50D", "#FF9933", "#E56B38", "#B83230", "#5C1918"]
    ragweed_pollen: ["#EFEEEC", "#A0D7FF", "#FEF6CD", "#FBEC9B", "#FAC50D", "#FF9933", "#E56B38", "#B83230", "#5C1918"]
  contour_levels:
    ozone: [0, 80, 120, 180, 240, 1000]
    particulate_matter_2.5um: [0, 15, 30, 40, 90, 1000]
    particulate_matter_10um: [0, 35, 60, 90, 180, 1000]
    nitrogen_dioxide: [0, 40, 100, 200, 400, 1000]
    alder_pollen:  [0, 1, 5, 10, 25, 50, 100, 500, 1000, 5000, 100000]
    birch_pollen:  [0, 1, 5, 10, 25, 50, 100, 500, 1000, 5000, 100000]
    grass_pollen:  [0, 1, 5, 10, 25, 50, 100, 500, 1000, 100000]
    mugwort_pollen:  [0, 1, 5, 10, 25, 50, 100, 500, 1000, 5000, 100000]
    olive_pollen:  [0, 1, 5, 10, 25, 50, 100, 500, 1000, 5000, 100000]
    ragweed_pollen:  [0, 1, 5, 10, 25, 50, 100, 500, 1000, 100000]
web:
  colours:
    alder_pollen: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    ammonia: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    birch_pollen: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    carbon_monoxide: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    dust: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    formaldehyde: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    glyoxal: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    grass_pollen: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    mugwort_pollen: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    nitrogen_dioxide: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    nitrogen_monoxide: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    non_methane_vocs: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    olive_pollen: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    ozone: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    particulate_matter_10um: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    particulate_matter_2.5um: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    peroxyacyl_nitrates: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    pm10_sea_salt_dry: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    pm10_wildfires: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    pm2.5_ammonium:  ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    pm2.5_nitrate:  ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    pm2.5_sulphate:  ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    pm2.5_total_organic_matter:  ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    ragweed_pollen: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    residential_elementary_carbon: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    secondary_inorganic_aerosol: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    sulphur_dioxide: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
    total_elementary_carbon: ["#C7EAF4", "#B4E0EC", "#A1D6E4", "#C0E0CE", "#ECEFB4", "#FBE98F", "#F6D463", "#EEB53D", "#E28721", "#D15D0C", "#AB4211", "#862716"]
  contour_levels:
    ammonia: [0.0, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 1.5, 2.0, 5.0, 10.0, 20.0]
    birch_pollen: [0.0, 1.0, 5.0, 10.0, 50.0, 100.0, 500.0, 1000.0, 2000.0, 5000.0, 10000.0, 20000.0, 200000.0]
    carbon_monoxide: [0.0, 50.0, 100.0, 150.0, 200.0, 250.0, 300.0, 350.0, 400.0, 500.0, 700.0, 1000.0, 2000.0]
    dust: [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 500.0]
    formaldehyde: [0.0, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 1.5, 2.0, 5.0, 10.0, 20.0]
    glyoxal: [0.0, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 1.5, 2.0, 5.0, 10.0, 20.0]
    grass_pollen: [0.0, 1.0, 5.0, 10.0, 50.0, 100.0, 500.0, 1000.0, 2000.0, 5000.0, 10000.0, 20000.0, 200000.0]
    mugwort_pollen: [0.0, 1.0, 5.0, 10.0, 50.0, 100.0, 500.0, 1000.0, 2000.0, 5000.0, 10000.0, 20000.0, 200000.0]
    nitrogen_dioxide: [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 300.0]
    nitrogen_monoxide: [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 300.0]
    non_methane_vocs: [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 300.0]
    olive_pollen: [0.0, 1.0, 5.0, 10.0, 50.0, 100.0, 500.0, 1000.0, 2000.0, 5000.0, 10000.0, 20000.0, 200000.0]
    ozone: [0.0, 20.0, 40.0, 60.0, 80.0, 100.0, 120.0, 140.0, 160.0, 180.0, 200.0, 240.0, 500.0]
    particulate_matter_10um: [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 500.0]
    particulate_matter_2.5um: [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 500.0]
    peroxyacyl_nitrates: [0.0, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 1.5, 2.0, 5.0, 10.0, 20.0]
    pm10_sea_salt_dry: [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 500.0]
    pm10_wildfires: [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 500.0]
    pm2.5_ammonium:  [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 500.0]
    pm2.5_nitrate:  [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 500.0]
    pm2.5_sulphate:  [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 500.0]
    pm2.5_total_organic_matter:  [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 500.0]
    ragweed_pollen: [0.0, 1.0, 5.0, 10.0, 50.0, 100.0, 500.0, 1000.0, 2000.0, 5000.0, 10000.0, 20000.0, 200000.0]
    residential_elementary_carbon: [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 500.0]
    secondary_inorganic_aerosol: [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 500.0]
    sulphur_dioxide: [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 800.0]
    total_elementary_carbon: [0.0, 2.0, 5.0, 10.0, 20.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0, 500.0]
  
